version: "3.9"

services:
  jenkins:
    image: jenkins/jenkins:lts
    networks:
      - traefik-public
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    volumes:
      - jenkins_data:/var/jenkins_home
    deploy:
      placement:
        constraints:
          - node.role == worker
      labels:
        - traefik.enable=true
        - traefik.http.routers.jenkins.rule=PathPrefix(`/jenkins`)
        - traefik.http.services.jenkins.loadbalancer.server.port=8080

volumes:
  jenkins_data:

networks:
  traefik-public:
    external: true
