version: "3.9"

services:
  portainer:
    image: portainer/portainer-ce:latest
    networks:
      - traefik-public
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - target: 9000
        published: 9000
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

volumes:
  portainer_data:

networks:
  traefik-public:
    external: true
