version: "3.9"

services:
  sonarqube:
    image: sonarqube:lts-community
    networks:
      - traefik-public
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_WEB_CONTEXT: /sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    deploy:
      placement:
        constraints:
          - node.role == worker
      labels:
        - traefik.enable=true
        - traefik.http.routers.sonar.rule=PathPrefix(`/sonar`)
        - traefik.http.services.sonar.loadbalancer.server.port=9000

  db:
    image: postgres:15
    networks:
      - traefik-public
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.role == worker

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgres_data:

networks:
  traefik-public:
    external: true
